### ISSUE TITLE
20210806问题解决了么？  我要冲  

### ISSUE THREAD

**Issue by SparkCD** [BY2HIT/usdx-arduino#1]
有没有群啊？ 我还是喜欢三明治结构的

**Comment by bg2bhc** [comment]
应该都改过来了，文件已经更新了，不过我们的新样机还没回来。暂时没有搞群。

**Comment by SparkCD** [comment]
为什么屏幕I2c接到io那边去了？ 还可以io模拟i2c的嘛？   UNO SDA SDL不是A4 A5口么？  而且线也太靠外了。。。

**Comment by Kerry-Huang** [comment]
原版程序OLED的确是模拟I2C，第一版样机就被这个坑了。。。
走线的确有不合理之处，等第二版样机回来后可以再优化一下

**Comment by SparkCD** [comment]
好的  机器很漂亮   就冲这个了~
