### ISSUE TITLE
RF板的PC4_SDA    PC5_SCL 没有连接是留着飞线么？

### ISSUE THREAD

**Issue by SparkCD** [BY2HIT/usdx-arduino#3]

**Comment by bg2bhc** [comment]
那两条线不用连，从另一侧连过去了

SparkCD ***@***.***> 於 2021年8月26日 週四 上午1:59寫道：

**Comment by SparkCD** [comment]
没看到啊   只看到做了上拉

**Comment by bg2bhc** [comment]
在AD1接插件上，arduino板上这两个是连到一起的

SparkCD ***@***.***> 於 2021年8月26日 週四 上午11:11寫道：

**Comment by ZhouChangwei88** [comment]
请问C21与C37确实是空着的吗
