### ISSUE TITLE
您好，原理图上电容C21、C37的容值没有标明

### ISSUE THREAD

**Issue by ns123** [BY2HIT/usdx-arduino#4]
如题

**Comment by BG6TNB** [comment]
您好，请问 C21、C37 两颗电容是可以不装么？如果需要装的话，容值您现在知道了么？

**Comment by bg2bhc** [comment]
你好 ，这两个电容位置是预留的  ，完全按我们提供的图纸做这两个电容不装就可以了

BG6TNB ***@***.***> 於 2023年3月4日 週六 下午8:49寫道：

**Comment by BG6TNB** [comment]
非常感谢您在百忙之中的回复，我已经明白复刻不需要安装这两颗电容了。如果可以方便给我一点关键字，我去查一下这两个预留电容是做什么的、在系统中起什么作用么？最后非常感谢您在开源领域做出的贡献，感恩。在 2023年3月5日，16:42，bg2bhc ***@***.***> 写道：﻿
你好 ，这两个电容位置是预留的  ，完全按我们提供的图纸做这两个电容不装就可以了



BG6TNB ***@***.***> 於 2023年3月4日 週六 下午8:49寫道：

**Comment by bg2bhc** [comment]
您好，C21可以跳过低通滤波器，对于一些只需要接收并且需要降低成本的场合，可以低通和继电器都不装，只要装了C21就仍然可以接收。C37是低通滤波器的一部分，有的频段的滤波器需要用非标准的电容值，这就需要两个电容并联，C37所在的频段不需要并联。

BG6TNB ***@***.***> 於 2023年3月5日 週日 下午7:16寫道：

**Comment by BG6TNB** [comment]
学习了，非常感谢您的回复。73在 2023年3月6日，10:00，bg2bhc ***@***.***> 写道：﻿
您好，C21可以跳过低通滤波器，对于一些只需要接收并且需要降低成本的场合，可以低通和继电器都不装，只要装了C21就仍然可以接收。C37是低通滤波器的一部分，有的频段的滤波器需要用非标准的电容值，这就需要两个电容并联，C37所在的频段不需要并联。



BG6TNB ***@***.***> 於 2023年3月5日 週日 下午7:16寫道：
